apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app-b-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/miltalex/poc-flux
  ref:
    branch: main
