apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: poc-flux
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/miltalex/poc-flux
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/kind/flux-system/
  prune: true
  sourceRef:
    kind: GitRepository
    name: poc-flux
