apiVersion: v1
kind: Namespace
metadata:
  name: app-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
  namespace: app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: app-a
        image: nginx:latest
        ports:
        - containerPort: 81

---
apiVersion: v1
kind: Service
metadata:
  name: app-a
  namespace: app-a
spec:
  selector:
    app: app-a
  ports:
  - port: 81
    targetPort: 81
