apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app-c
  namespace: flux-system
spec:
  interval: 5m
  path: "./apps/app-c"
  prune: true
  sourceRef:
    kind: GitRepository
    name: app-c-repo
  targetNamespace: app-c
